### ISSUE TITLE
[SOLVED] NoSuchMethodError when using ParagraphCell

### ISSUE THREAD

**Issue by shrap42** [vandeseer/easytable#142]
I got this:
`java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotation.constructAppearances()V
	at org.vandeseer.easytable.drawing.cell.ParagraphCellDrawer.drawContent(ParagraphCellDrawer.java:57)
	at org.vandeseer.easytable.TableDrawer.lambda$new$0(TableDrawer.java:69)
	at org.vandeseer.easytable.TableDrawer.drawRow(TableDrawer.java:200)
	at org.vandeseer.easytable.TableDrawer.drawWithFunction(TableDrawer.java:183)
	at org.vandeseer.easytable.TableDrawer.lambda$drawPage$1(TableDrawer.java:91)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.vandeseer.easytable.TableDrawer.drawPage(TableDrawer.java:90)
	at org.vandeseer.easytable.TableDrawer.draw(TableDrawer.java:157)
	at cz.fineship.finepoint.KufiPoC.testEasyParagraphTable(KufiPoC.java:297)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
`
when trying to use ParagraphCell. I used you example method createParagraphTable() from this file https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/ParagraphCellTest.java. I have this 
`<dependency>
  <groupId>com.github.vandeseer</groupId>
  <artifactId>easytable</artifactId>
  <version>0.8.5</version>
</dependency>
<dependency>
  <groupId>com.github.ralfstuckert.pdfbox-layout</groupId>
  <artifactId>pdfbox2-layout</artifactId>
  <version>1.0.1</version>
</dependency>`
 in pom.xml with the jitpack.io repository set. Is there anything I am missing?

**Comment by shrap42** [comment]
Turned out I need newer PDFBOX version. I had 2.0.4, went to 2.0.24 and it works!
