### ISSUE TITLE
Paragraph in a cell

### ISSUE THREAD

**Issue by buzzer83** [vandeseer/easytable#67]
I am using your EasyTable library and it is fantastic, for my use it is better than itext7. I have only one problem. I'm trying to insert a paragraph with multiple lines inside a cell but it gives me an error. Here is my class.

The error is:

`Exception in thread "main" java.lang.NullPointerException
        at org.vandeseer.easytable.drawing.cell.ParagraphCellDrawer.drawContent(ParagraphCellDrawer.java:52)
        at org.vandeseer.easytable.TableDrawer.lambda$new$0(TableDrawer.java:53)
        at org.vandeseer.easytable.TableDrawer.drawRow(TableDrawer.java:161)
        at org.vandeseer.easytable.TableDrawer.drawWithFunction(TableDrawer.java:145)
        at org.vandeseer.easytable.TableDrawer.lambda$drawPage$1(TableDrawer.java:75)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.vandeseer.easytable.TableDrawer.drawPage(TableDrawer.java:74)
        at org.vandeseer.easytable.TableDrawer.draw(TableDrawer.java:70)
        at it.baz.ProvaPDF.crea(ProvaPDF.java:66)
        at it.baz.ProvaPDF.main(ProvaPDF.java:21)`

'
[ProvaPDF.txt](https://github.com/vandeseer/easytable/files/4225709/ProvaPDF.txt)

[pom.xml.txt](https://github.com/vandeseer/easytable/files/4225717/pom.xml.txt)

Thank you

**Comment by vandeseer** [comment]
Hi @buzzer83, 

glad that you find the library useful. 😃 
I will have a look at the issue soon. 

Best,
Stefan

**Comment by vandeseer** [comment]
The solution is as simple as: 

            TableDrawer tableDrawer = TableDrawer.builder()
                    .contentStream(contentStream)
                    .page(page) // <-- This was missing
                    .startX((page.getMediaBox().getUpperRightX() - 200) / 2)
                    .startY(page.getMediaBox().getUpperRightY() - 20)
                    .table(myTable)
                    .build();

I mentioned this for the use of links in the README: https://github.com/vandeseer/easytable#enable-links but I just realized that one would also need it for using any `ParagraphCell`. As I stated in the README as well: This whole thingy is a bit experimental. But I think I will add some more meaningful exception and or message so that it's easier to catch this issue :wink:

**Comment by buzzer83** [comment]
Thanks you.
